# Generated by Django 5.2.1 on 2025-05-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessages",
            name="token_usage",
            field=models.IntegerField(default=0),
        ),
    ]
