# Generated by Django 5.2.1 on 2025-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_chatmessages_token_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessages",
            name="function_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
